import Head from 'next/head';
import type { FC } from 'react';
interface head {
    title: string;

}
const HeadPage: FC<head> = (props: head) => {
    return (
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>

    )

}
export default HeadPage